# Generated by Django 5.1.6 on 2025-03-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("property", "0004_alter_image_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("amount", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("message", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejeceted"),
                        ],
                        default="APPLIED",
                        max_length=30,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements_as_applicant",
                        to="core.rentaluser",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements_as_landlord",
                        to="core.rentaluser",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
