# Generated by Django 5.1.6 on 2025-03-27 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link", models.CharField(max_length=500)),
                ("amount", models.IntegerField()),
                ("is_successful", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
