# Generated by Django 5.1.6 on 2025-03-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agreement", "0001_initial"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="is_successful",
        ),
        migrations.AddField(
            model_name="payment",
            name="agreement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="agreement.agreement",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("SUCCESFUL", "Successful"),
                    ("FAILED", "Failed"),
                ],
                default="INITIATED",
                max_length=40,
            ),
        ),
    ]
