# Generated by Django 5.1.6 on 2025-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_remove_payment_is_successful_payment_agreement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("URL_FAILED", "Url Failed"),
                    ("URL_SUCCESFULL", "Url Successful"),
                    ("SUCCESFUL", "Successful"),
                    ("FAILED", "Failed"),
                ],
                default="INITIATED",
                max_length=40,
            ),
        ),
    ]
