# Generated by Django 5.1.6 on 2025-03-04 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("APARTMENT", "Apartment"), ("HOUSE", "House")],
                        default="APARTMENT",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("price", models.BigIntegerField()),
                ("thumbnail", models.ImageField(upload_to="thumbnail")),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.rentaluser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="properties")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="property.property",
                    ),
                ),
            ],
        ),
    ]
