# Generated by Django 5.1.6 on 2025-03-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="area",
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="bathrooms_count",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms_count",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="can_accomodate",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="facts",
            field=models.JSONField(default="asdsad"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="location",
            field=models.CharField(
                choices=[
                    ("KATHMANDU", "Kathmandu"),
                    ("BHAKTAPUR", "Bhaktapur"),
                    ("LALITPUR", "Lalitpur"),
                ],
                default="KATHMANDU",
                max_length=15,
            ),
        ),
    ]
