# Generated by Django 5.1.6 on 2025-03-28 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0004_alter_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
